// <auto-generated />
using System;
using CRUD2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD2.Migrations
{
    [DbContext(typeof(MVCDemoDbContext))]
    [Migration("20240114081902_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUD2.Models._21_22.BaiHat", b =>
                {
                    b.Property<string>("MaBaiHat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenBaiHat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBaiHat");

                    b.ToTable("BaiHat");
                });

            modelBuilder.Entity("CRUD2.Models._21_22.CaSi", b =>
                {
                    b.Property<string>("MaCaSi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCaSi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCaSi");

                    b.ToTable("CaSi");
                });

            modelBuilder.Entity("CRUD2.Models._21_22.CaSi_BaiHat", b =>
                {
                    b.Property<string>("MaCaSi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBaiHat")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaCaSi", "MaBaiHat");

                    b.ToTable("CaSi_BaiHat");
                });

            modelBuilder.Entity("CRUD2.Models._21_22.NguoiNghe", b =>
                {
                    b.Property<string>("MaNguoiNghe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("TenNN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiNghe");

                    b.ToTable("NguoiNghe");
                });

            modelBuilder.Entity("CRUD2.Models._21_22.PlayList", b =>
                {
                    b.Property<string>("MaPlayList")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenPlayList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPlayList");

                    b.ToTable("PlayList");
                });

            modelBuilder.Entity("CRUD2.Models._21_22.PlayList_BaiHat", b =>
                {
                    b.Property<string>("MaPlayList")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBaiHat")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaPlayList", "MaBaiHat");

                    b.ToTable("PlayList_BaiHat");
                });

            modelBuilder.Entity("CRUD2.Models.Departments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_Departments");
                });

            modelBuilder.Entity("CRUD2.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Salary")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CRUD2.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DepID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_Student");
                });
#pragma warning restore 612, 618
        }
    }
}
